language: node_js

node_js:
  - node
  - "12"
  - "14"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lamy_test;'

script:
  - npx @commitlint/travis-cli
  - npm run build
  - npm test -- --coverage
  - npx codecov
