name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["12.x", "14.x", "16.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Execute linter
        run: npm run lint
      # Sleeping for 10 seconds to wait for the databases
      - name: Run database containers
        run: npm run docker:up && sleep 10
      - name: Run tests
        run: npm test -- --coverage
      - name: Build TypeScript
        run: npm run build
      - name: Build documentation
        run: npm run docs
